VERIFICATION_PROMPT = """You are reviewing an answer generated by an AI system.

Original question:
{QUESTION}

Generated answer:
{GENERATED_TEXT}

Carefully check the generated answer against the original question.

If the generated answer is correct, output it unchanged.

If the generated answer is incorrect, incomplete, or contains a substantive error, produce a corrected answer.

Your output must contain ONLY the answer that should ultimately be given to the user.
Do not provide an explanation of your checking process.
Do not mention that you reviewed or revised the answer.
Do not change the answer merely because you would phrase it differently."""